# Google Cloud Build configuration for Cloud Run deployment
steps:
  # 1. Container Image Oluştur (Build)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/smartsupport-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/smartsupport-backend:latest'
      - '.'

  # 2. Container Image'ı Kayıt Defterine Gönder (Push)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/smartsupport-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/smartsupport-backend:latest'

  # 3. Cloud Run'a Deploy Et (KRİTİK AYARLAR BURADA)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'  # 'beta' komutlarını kullanmak daha güvenli (no-cpu-throttling için)
      - 'run'
      - 'deploy'
      - 'smartsupport-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/smartsupport-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west3'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      # 👇 DÜZELTİLEN AYARLAR 👇
      - '--memory'
      - '8Gi'          # 4Gi YERİNE 8Gi YAPTIK
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'            # Soğuk başlangıcı önlemek için
      - '--max-instances'
      - '1'            # KOTA AŞMAMAK İÇİN 10 YERİNE 1 YAPTIK
      - '--no-cpu-throttling' # Worker çalışsın diye CPU'yu kesme dedik
      - '--vpc-connector'
      - 'redis-connector'     # Redis'e ulaşabilmesi için köprüyü ekledik
      # 👆 DÜZELTİLEN AYARLAR BİTTİ 👆
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/smartsupport-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/smartsupport-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'