# Google Cloud Build configuration for Cloud Run deployment
# Build and deploy the containerized application

steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/smartsupport-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/smartsupport-backend:latest'
      - '.'

  # Push container image to registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/smartsupport-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/smartsupport-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'smartsupport-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/smartsupport-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west3'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--memory'
      - '8Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'
      - '--no-cpu-throttling'
      - '--vpc-connector'
      - 'redis-connector'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/smartsupport-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/smartsupport-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'

